champions = {
    "champions":"",
    "tournament":{
        "champions ":{
            "date":["",""],
            "participants":[

            ],
            "results":{
                "group_stage":[
                    {
                        "opening":[
                            {},
                            {}
                        ],
                        "winners":{},
                        "elimination":{},
                        "decider":{}
                    },
                    {
                        "opening":[
                            {},
                            {}
                        ],
                        "winners":{},
                        "elimination":{},
                        "decider":{}
                    },
                    {
                        "opening":[
                            {},
                            {}
                        ],
                        "winners":{},
                        "elimination":{},
                        "decider":{}
                    },
                    {
                        "opening":[
                            {},
                            {}
                        ],
                        "winners":{},
                        "elimination":{},
                        "decider":{}
                    }
                ],
                "playoffs_stage":{
                    "upper_quarterfinals":[
                        {},
                        {},
                        {},
                        {}
                    ],
                    "upper_semifinals":[
                        {},
                        {}
                    ],
                    "upper_final":{},
                    "lower_round_1":[
                        {},
                        {}
                    ],
                    "lower_round_2":[
                        {},
                        {}
                    ],
                    "lower_semifinal":{},
                    "lower_final":{},
                    "grand_final":{}
                }
            }
        }
    }
}